### ISSUE TITLE
Spike : Z-score Calculation

### ISSUE THREAD

**Issue by deepak-quovantis** [thinkarlabs/P23-004-MalnutritionAwareness#72]

**Comment by sumit-rawat-quo** [comment]
Z-score for weight-for-height needs to be calculated based on Indian standards (not WHO). 
So initial research around z-score calculation doesn't come handy. See the references below
https://www.fantaproject.org/sites/default/files/download/Calculate-WHZ-2.6-NACS-Users-Guide-Apr2016.pdf
https://emids.sharepoint.com/:b:/r/sites/Malnutrition-MobileApp/Shared%20Documents/General/Malnutrition%20Algo%20Hunt%20-%20Using%20Chat%20GPT-2.pdf?csf=1&web=1&e=QzJXcC

Second approach around calculating the z-scores for SAM/MAM was to consume poshan tracker API. 
Website has disabled right-click and inspect element so got around it through browser developer tools.
Tried consuming the API but looks like for every unique calculation request, it generates a unique authorization token and returns encoded response. 
Tried decoding the encoded response through gzip but yet to decode it successfully. 

For now, as discussed with Praveen, we are going ahead with simple sam/mam/normal dropdown on temporary basis until Praveen comes back with the z-score formula with Indian Standards.
